<a href="https://colab.research.google.com/github/rezandiadiatma/datamining/blob/main/TugasPertemuan3_DataPreprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('DataTugas.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(x)

[['Avanza' 2015.0 158000.0]
 ['Xenia' 2020.0 174000.0]
 ['Avanza' 2010.0 146000.0]
 ['Xenia' 2016.0 nan]
 ['Brio' 2015.0 140000.0]
 ['Brio' nan 155000.0]
 ['Avanza' 2020.0 180000.0]
 ['Brio' 2019.0 168000.0]
 ['Avanza' 2016.0 170000.0]
 ['Xenia' 2013.0 147000.0]]


In [4]:
print(y)

['Kosong' 'Kosong' 'Tersedia' 'Kosong' 'Tersedia' 'Kosong' 'Kosong'
 'Tersedia' 'Kosong' 'Tersedia']


In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [6]:
print(x)

[['Avanza' 2015.0 158000.0]
 ['Xenia' 2020.0 174000.0]
 ['Avanza' 2010.0 146000.0]
 ['Xenia' 2016.0 159777.77777777778]
 ['Brio' 2015.0 140000.0]
 ['Brio' 2016.0 155000.0]
 ['Avanza' 2020.0 180000.0]
 ['Brio' 2019.0 168000.0]
 ['Avanza' 2016.0 170000.0]
 ['Xenia' 2013.0 147000.0]]


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encode', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [8]:
print(x)

[[1.0 0.0 0.0 2015.0 158000.0]
 [0.0 0.0 1.0 2020.0 174000.0]
 [1.0 0.0 0.0 2010.0 146000.0]
 [0.0 0.0 1.0 2016.0 159777.77777777778]
 [0.0 1.0 0.0 2015.0 140000.0]
 [0.0 1.0 0.0 2016.0 155000.0]
 [1.0 0.0 0.0 2020.0 180000.0]
 [0.0 1.0 0.0 2019.0 168000.0]
 [1.0 0.0 0.0 2016.0 170000.0]
 [0.0 0.0 1.0 2013.0 147000.0]]


In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
print(y)

[0 0 1 0 1 0 0 1 0 1]


In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=1)

In [12]:
print(x_train)

[[1.0 0.0 0.0 2020.0 180000.0]
 [0.0 1.0 0.0 2015.0 140000.0]
 [1.0 0.0 0.0 2015.0 158000.0]
 [0.0 0.0 1.0 2016.0 159777.77777777778]
 [0.0 0.0 1.0 2020.0 174000.0]
 [0.0 1.0 0.0 2019.0 168000.0]
 [1.0 0.0 0.0 2016.0 170000.0]
 [0.0 1.0 0.0 2016.0 155000.0]]


In [13]:
print(x_test)

[[1.0 0.0 0.0 2010.0 146000.0]
 [0.0 0.0 1.0 2013.0 147000.0]]


In [14]:
print(y_train)

[0 1 0 0 0 1 0 0]


In [15]:
print(y_test)

[1 1]


In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [17]:
print(x_train)

[[1.0 0.0 0.0 1.418240756749877 1.4334769726577727]
 [0.0 1.0 0.0 -1.0482649071629526 -1.9588103578717133]
 [1.0 0.0 0.0 -1.0482649071629526 -0.43228105913344467]
 [0.0 0.0 1.0 -0.5549637743803867 -0.2815127333321339]
 [0.0 0.0 1.0 1.418240756749877 0.9246338730783498]
 [0.0 1.0 0.0 0.9249396239673111 0.41579077349892685]
 [1.0 0.0 0.0 -0.5549637743803867 0.5854051400254012]
 [0.0 1.0 0.0 -0.5549637743803867 -0.6867026089231562]]


In [18]:
print(x_test)

[[1.0 0.0 0.0 -3.514770571075782 -1.4499672582922905]
 [0.0 0.0 1.0 -2.0348671727280845 -1.3651600750290533]]
